### PR TITLE
Fix host is not being passed

### LINKED ISSUE #15: Problem in OpenShift
I'm trying to run chisel server on an OpenShift application but it fails. I think this is because Apache is listening on port 8080 by default (not sure).

Command:

```
./chisel server --host $OPENSHIFT_GO_IP --port $OPENSHIFT_GO_PORT --proxy http://example.com
```

Error:

`bind: address already in use`

### PR DESCRIPTION
**Pull request by KazeFlame**
Fix #15 too.

### CODE REVIEW

File: server/server.go [hunk 1]
```diff
@@ -106,7 +106,7 @@ func (s *Server) Start(host, port string) error {
 	}
 	s.Infof("Listening on %s...", port)
 
-	return s.httpServer.GoListenAndServe(":"+port, http.HandlerFunc(s.handleHTTP))
+	return s.httpServer.GoListenAndServe(host+":"+port, http.HandlerFunc(s.handleHTTP))
```
Comment (jpillora) [inline server/server.go]: Changes to lines 92,99 are unnecessary, though this looks good to me!

**Comment by KazeFlame** [comment]
Removed unnecessary changes. Sorry I'm new to Go. I'm still learning the language.

**Comment by jpillora** [comment]
No worries, thanks for the PR :)
