### PR TITLE
Bug fix and add --max-retry-interval option.

### LINKED ISSUE #48: [BUG] Server side reboot client side can't reconnect.

### PR DESCRIPTION
**Pull request by iineva**
* Solve #45
* Fix #48

### CODE REVIEW

File: client/client.go [hunk 1]
```diff
@@ -171,6 +176,7 @@ func (c *Client) loop() {
 		d := websocket.Dialer{
 			ReadBufferSize:  1024,
 			WriteBufferSize: 1024,
+			HandshakeTimeout: b.Duration(),
```
Comment (jpillora) [inline client/client.go]: What duration is this intended to be? `b.Duration` increments the backoff timer, though it's already being incremented when there's an error.

Comment (iineva) [reply client/client.go]: I use the same backoff timer for convenient. And logic is ok. Should we add another backoff timer to control `HandshakeTimeout`?

**Comment by jpillora** [comment]
Thanks! See commits for changes
